function LineIndex = CheckMissingPoint(TEXTFILE,SamplingRate)
% TEXTFILE is the raw text that generated by OceanView
% SamplingRate is the raw rate in the unit of Hz. 
% e.g. interleaved rate should be 20Hz.
% Weiting Zhang, 05/04/2022
% Tested with data generated with OceanView V1.5

tmp = detectImportOptions(TEXTFILE);
NumOfHeaderLines = tmp.DataLines(1,1); 
opts = detectImportOptions(TEXTFILE,'NumHeaderLines',NumOfHeaderLines);
t = readtable(TEXTFILE,opts);

TimeStamps = t.Var2;
Intervals = TimeStamps(2:end) - TimeStamps(1:(end-1));
LineIndex = find(Intervals > (1000/SamplingRate + 10));
LineIndex = LineIndex +1;


